import React, { useState } from 'react';
import {
    CheckCircle2, AlertCircle, Info, Clock, ExternalLink,
    List, MoreHorizontal, ChevronRight, FileDigit
} from 'lucide-react';

class WidgetErrorBoundary extends React.Component {
    constructor(props) {
        super(props);
        this.state = { hasError: false, error: null };
    }
    static getDerivedStateFromError(error) {
        return { hasError: true, error };
    }
    componentDidCatch(error, errorInfo) {
        console.error("Widget rendering error:", error, errorInfo);
    }
    render() {
        if (this.state.hasError) {
            return (
                <div className="p-3 mt-3 bg-red-50 text-red-800 rounded-xl text-sm font-medium border border-red-100">
                    <AlertCircle className="inline-block mr-2 text-red-500" size={16} />
                    Failed to render UI: {this.state.error?.message}
                </div>
            );
        }
        return this.props.children;
    }
}

/**
 * Renders the different UI widget block types returned by the AI.
 * Handles the 6 distinct types generated by the prompt.
 */
const DynamicUiWidget = ({ uiData, onAction }) => {
    if (!uiData || !uiData.type) return null;

    const { type, payload } = uiData;
    let widget = null;

    switch (type) {
        case 'result_card':
            widget = <ResultCard payload={payload || {}} />;
            break;
        case 'item_list':
            widget = <ItemList payload={payload || {}} onAction={onAction} />;
            break;
        case 'confirm_action':
            widget = <ConfirmAction payload={payload || {}} onAction={onAction} />;
            break;
        case 'workflow_stepper':
            widget = <WorkflowStepper payload={payload || {}} />;
            break;
        case 'quick_actions':
            widget = <QuickActions payload={payload || {}} onAction={onAction} />;
            break;
        case 'field_form':
            widget = <FieldForm payload={payload || {}} onAction={onAction} />;
            break;
        default:
            widget = (
                <div className="p-3 bg-red-50 text-red-600 rounded-xl text-sm font-medium border border-red-100">
                    Unknown UI widget type: {type}
                </div>
            );
    }

    return <WidgetErrorBoundary>{widget}</WidgetErrorBoundary>;
};

const ResultCard = ({ payload }) => {
    const statusColors = {
        success: "bg-emerald-50 text-emerald-800 border-emerald-100",
        error: "bg-red-50 text-red-800 border-red-100",
        warning: "bg-orange-50 text-orange-800 border-orange-100",
        info: "bg-blue-50 text-blue-800 border-blue-100"
    };

    const statusIcons = {
        success: <CheckCircle2 className="text-emerald-500 mb-2" size={24} />,
        error: <AlertCircle className="text-red-500 mb-2" size={24} />,
        warning: <AlertCircle className="text-orange-500 mb-2" size={24} />,
        info: <Info className="text-blue-500 mb-2" size={24} />
    };

    const colorClass = statusColors[payload.status || 'info'] || statusColors.info;
    const Icon = statusIcons[payload.status || 'info'] || statusIcons.info;

    return (
        <div className={`mt-3 p-4 rounded-2xl border ${colorClass} shadow-sm transition-all duration-300`}>
            {Icon}
            <h4 className="font-bold text-sm mb-1">{payload.title}</h4>
            {payload.details && typeof payload.details === 'object' && (
                <div className="space-y-1 mt-2">
                    {Object.entries(payload.details).map(([key, value]) => (
                        <div key={key} className="flex justify-between text-xs opacity-80">
                            <span className="font-medium capitalize">{key.replace(/_/g, ' ')}:</span>
                            <span className="font-bold">{value}</span>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
};

const ItemList = ({ payload, onAction }) => {
    return (
        <div className="mt-3 space-y-2">
            <h4 className="text-xs font-bold text-slate-500 uppercase tracking-widest ml-1 mb-2">{payload.title}</h4>
            {Array.isArray(payload.items) && payload.items.map((item, idx) => (
                <div
                    key={idx}
                    className="p-3 rounded-xl bg-white border border-slate-100 shadow-sm hover:shadow-md transition-shadow cursor-pointer flex justify-between items-center group"
                    onClick={() => item.action && onAction && onAction(item.action)}
                >
                    <div>
                        <div className="font-bold text-slate-800 text-sm">{item.title}</div>
                        {item.subtitle && <div className="text-xs text-slate-500 mt-0.5">{item.subtitle}</div>}
                    </div>
                    {item.action && (
                        <ChevronRight size={16} className="text-slate-300 group-hover:text-blue-500 transition-colors" />
                    )}
                </div>
            ))}
        </div>
    );
};

const ConfirmAction = ({ payload, onAction }) => {
    return (
        <div className="mt-3 p-4 bg-white border border-blue-100 rounded-2xl shadow-sm">
            <h4 className="font-bold text-blue-900 text-sm mb-3 flex items-center gap-2">
                <Info size={16} className="text-blue-500" />
                {payload.title}
            </h4>

            <div className="bg-slate-50 rounded-xl p-3 mb-4 space-y-2 border border-slate-100">
                {payload.data && typeof payload.data === 'object' && Object.entries(payload.data).map(([key, value]) => (
                    <div key={key} className="flex justify-between text-xs">
                        <span className="text-slate-500 font-medium capitalize">{key.replace(/_/g, ' ')}</span>
                        <span className="text-slate-800 font-bold">{String(value)}</span>
                    </div>
                ))}
            </div>

            <div className="flex gap-2">
                {Array.isArray(payload.actions) && payload.actions.map((action, idx) => (
                    <button
                        key={idx}
                        onClick={() => onAction && onAction(action.value)}
                        className={`flex-1 py-2.5 rounded-xl text-xs font-bold transition-all shadow-sm ${action.type === 'primary'
                            ? 'bg-blue-600 text-white hover:bg-blue-700 hover:shadow-md'
                            : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
                            }`}
                    >
                        {action.label}
                    </button>
                ))}
            </div>
        </div>
    );
};

const WorkflowStepper = ({ payload }) => {
    return (
        <div className="mt-3 p-4 bg-white border border-slate-100 rounded-2xl shadow-sm">
            <h4 className="font-bold text-slate-800 text-sm mb-4">{payload.title}</h4>
            <div className="space-y-4">
                {Array.isArray(payload.steps) && payload.steps.map((step, idx) => (
                    <div key={idx} className="flex gap-3 items-start relative">
                        {/* Connecting Line */}
                        {idx !== payload.steps.length - 1 && (
                            <div className="absolute left-3.5 top-8 bottom-[-16px] w-0.5 bg-slate-100 z-0"></div>
                        )}

                        {/* Step Icon */}
                        <div className={`relative z-10 w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0 ${step.status === 'completed' ? 'bg-emerald-100 text-emerald-600' :
                            step.status === 'active' ? 'bg-blue-600 text-white shadow-md ring-4 ring-blue-50' :
                                'bg-slate-100 text-slate-400'
                            }`}>
                            {step.status === 'completed' ? <CheckCircle2 size={14} /> :
                                step.status === 'active' ? <Clock size={14} /> :
                                    <div className="w-1.5 h-1.5 rounded-full bg-slate-400" />}
                        </div>

                        {/* Step Content */}
                        <div className={`pt-1 pb-2 ${step.status === 'pending' ? 'opacity-50' : ''}`}>
                            <div className={`text-sm font-bold ${step.status === 'active' ? 'text-blue-900' : 'text-slate-700'}`}>
                                {step.label}
                            </div>
                            {step.details && <div className="text-xs text-slate-500 mt-0.5">{step.details}</div>}
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
};

const QuickActions = ({ payload, onAction }) => {
    return (
        <div className="mt-3 flex flex-wrap gap-2">
            {Array.isArray(payload.actions) && payload.actions.map((action, idx) => (
                <button
                    key={idx}
                    onClick={() => onAction && onAction(action.value)}
                    className="px-3 py-1.5 bg-white border border-slate-200 rounded-full text-xs font-bold text-slate-600 hover:border-blue-400 hover:text-blue-600 hover:bg-blue-50 transition-all shadow-sm"
                >
                    {action.label}
                </button>
            ))}
        </div>
    );
};

const FieldForm = ({ payload, onAction }) => {
    const [formData, setFormData] = useState({});

    const handleSumbit = (e) => {
        e.preventDefault();
        if (onAction) {
            // Pass back the form data along with the submit action value if defined
            onAction({ action: payload.submitAction || 'submit_form', data: formData });
        }
    };

    return (
        <div className="mt-3 p-4 bg-white border border-slate-100 rounded-2xl shadow-sm">
            <h4 className="font-bold text-slate-800 text-sm mb-3">{payload.title}</h4>
            <form onSubmit={handleSumbit}>
                <div className="space-y-3 mb-4">
                    {Array.isArray(payload.fields) && payload.fields.map((field) => (
                        <div key={field.id}>
                            <label className="block text-xs font-bold text-slate-500 mb-1 ml-1">{field.label}</label>
                            {field.type === 'select' ? (
                                <select
                                    className="w-full bg-slate-50 border border-slate-200 rounded-xl px-3 py-2 text-sm text-slate-800 font-medium focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-all"
                                    onChange={(e) => setFormData({ ...formData, [field.id]: e.target.value })}
                                    defaultValue={field.defaultValue || ""}
                                >
                                    <option value="" disabled>Select {field.label}</option>
                                    {field.options?.map(opt => (
                                        <option key={opt.value} value={opt.value}>{opt.label}</option>
                                    ))}
                                </select>
                            ) : (
                                <input
                                    type={field.type || "text"}
                                    className="w-full bg-slate-50 border border-slate-200 rounded-xl px-3 py-2 text-sm text-slate-800 font-medium focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-all placeholder:text-slate-400 placeholder:font-normal"
                                    placeholder={field.placeholder || ""}
                                    defaultValue={field.defaultValue || ""}
                                    onChange={(e) => setFormData({ ...formData, [field.id]: e.target.value })}
                                />
                            )}
                        </div>
                    ))}
                </div>
                <button
                    type="submit"
                    className="w-full py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-sm font-bold shadow-md shadow-blue-500/20 transition-all"
                >
                    {payload.submitLabel || "Submit"}
                </button>
            </form>
        </div>
    );
};

export default DynamicUiWidget;
