openapi: 3.0.0
info: {title: Warehouse - Read (A2X), version: 1.0.1, description: This allows you to integrate input help (F4 help) for warehouse numbers in your mobile apps.}
externalDocs: {description: Business Documentation, url: 'https://help.sap.com/http.svc/ahp2/SAP_S4HANA_CLOUD/2602.latest/EN/c5/ebd7bcfa9a43fd9133b64024ab4ac3/frameset.htm'}
x-sap-api-type: ODATAV4
x-sap-shortText: Retrieve warehouse numbers with this synchronous inbound service
x-sap-software-min-version: '2602'
x-sap-ext-overview:
- name: Communication Scenario
  values:
  - {text: Warehousing - Master Data Integration (SAP_COM_0374), format: plain}
- name: Scope Items
  values:
  - {text: '[Warehouse Inbound Processing (3BR)](https://me.sap.com/processnavigator/SolP/3BR " Link To BP ")', format: markdown}
  - {text: '[Resource Management in Warehousing (3W0)](https://me.sap.com/processnavigator/SolP/3W0 " Link To BP ")', format: markdown}
- name: Authentication Methods
  values:
  - {text: x509, format: plain}
- name: Service Group Name
  values:
  - {text: API_WAREHOUSE_2, format: plain}
- name: Business Object
  values:
  - {text: Warehouse, format: plain}
servers:
- url: https://{host}:{port}/sap/opu/odata4/sap/api_warehouse_2/srvd_a2x/sap/warehouse/0001
  variables:
    host: {default: ''}
    port: {default: ''}
- {url: 'https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata4/sap/api_warehouse_2/srvd_a2x/sap/warehouse/0001'}
x-sap-extensible: {supported: 'no'}
tags:
- {name: Warehouse}
- {name: Warehouse Storage Type}
paths:
  /Warehouse:
    get:
      summary: Get entities from Warehouse
      tags: [Warehouse]
      parameters:
      - {$ref: '#/components/parameters/top'}
      - {$ref: '#/components/parameters/skip'}
      - name: $filter
        in: query
        description: Filter items by property values, see [Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)
        schema: {type: string}
      - {$ref: '#/components/parameters/count'}
      - name: $orderby
        in: query
        description: Order items by property values, see [Sorting](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionorderby)
        explode: false
        schema:
          type: array
          uniqueItems: true
          items:
            type: string
            enum: [EWMWarehouse, EWMWarehouse desc]
      - name: $select
        in: query
        description: Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect)
        explode: false
        schema:
          type: array
          uniqueItems: true
          items:
            type: string
            enum: [EWMWarehouse]
      - name: $expand
        in: query
        description: Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand)
        explode: false
        schema:
          type: array
          uniqueItems: true
          items:
            type: string
            enum: ['*', _WarehouseStorageType]
      responses:
        '200':
          description: Retrieved entities
          content:
            application/json:
              schema:
                title: Collection of WarehouseType
                type: object
                properties:
                  '@odata.count': {$ref: '#/components/schemas/count'}
                  value:
                    type: array
                    items: {$ref: '#/components/schemas/com.sap.gateway.srvd_a2x.api_warehouse_2.v0001.WarehouseType'}
        4XX: {$ref: '#/components/responses/error'}
  /Warehouse/{EWMWarehouse}:
    parameters:
    - name: EWMWarehouse
      in: path
      required: true
      description: Warehouse Number/Warehouse Complex
      schema: {type: string, maxLength: 4}
    get:
      summary: Get entity from Warehouse by key
      tags: [Warehouse]
      parameters:
      - name: $select
        in: query
        description: Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect)
        explode: false
        schema:
          type: array
          uniqueItems: true
          items:
            type: string
            enum: [EWMWarehouse]
      - name: $expand
        in: query
        description: Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand)
        explode: false
        schema:
          type: array
          uniqueItems: true
          items:
            type: string
            enum: ['*', _WarehouseStorageType]
      responses:
        '200':
          description: Retrieved entity
          content:
            application/json:
              schema: {$ref: '#/components/schemas/com.sap.gateway.srvd_a2x.api_warehouse_2.v0001.WarehouseType'}
        4XX: {$ref: '#/components/responses/error'}
  /Warehouse/{EWMWarehouse}/_WarehouseStorageType:
    parameters:
    - name: EWMWarehouse
      in: path
      required: true
      description: Warehouse Number/Warehouse Complex
      schema: {type: string, maxLength: 4}
    get:
      summary: Get entities from related _WarehouseStorageType
      tags: [Warehouse, Warehouse Storage Type]
      parameters:
      - {$ref: '#/components/parameters/top'}
      - {$ref: '#/components/parameters/skip'}
      - name: $filter
        in: query
        description: Filter items by property values, see [Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)
        schema: {type: string}
      - {$ref: '#/components/parameters/count'}
      - name: $orderby
        in: query
        description: Order items by property values, see [Sorting](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionorderby)
        explode: false
        schema:
          type: array
          uniqueItems: true
          items:
            type: string
            enum: [EWMWarehouse, EWMWarehouse desc, EWMStorageType, EWMStorageType desc]
      - name: $select
        in: query
        description: Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect)
        explode: false
        schema:
          type: array
          uniqueItems: true
          items:
            type: string
            enum: [EWMWarehouse, EWMStorageType]
      - name: $expand
        in: query
        description: Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand)
        explode: false
        schema:
          type: array
          uniqueItems: true
          items:
            type: string
            enum: ['*', _Warehouse]
      responses:
        '200':
          description: Retrieved entities
          content:
            application/json:
              schema:
                title: Collection of WarehouseStorageTypeType
                type: object
                properties:
                  '@odata.count': {$ref: '#/components/schemas/count'}
                  value:
                    type: array
                    items: {$ref: '#/components/schemas/com.sap.gateway.srvd_a2x.api_warehouse_2.v0001.WarehouseStorageTypeType'}
        4XX: {$ref: '#/components/responses/error'}
  /WarehouseStorageType:
    get:
      summary: Get entities from WarehouseStorageType
      tags: [Warehouse Storage Type]
      parameters:
      - {$ref: '#/components/parameters/top'}
      - {$ref: '#/components/parameters/skip'}
      - name: $filter
        in: query
        description: Filter items by property values, see [Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)
        schema: {type: string}
      - {$ref: '#/components/parameters/count'}
      - name: $orderby
        in: query
        description: Order items by property values, see [Sorting](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionorderby)
        explode: false
        schema:
          type: array
          uniqueItems: true
          items:
            type: string
            enum: [EWMWarehouse, EWMWarehouse desc, EWMStorageType, EWMStorageType desc]
      - name: $select
        in: query
        description: Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect)
        explode: false
        schema:
          type: array
          uniqueItems: true
          items:
            type: string
            enum: [EWMWarehouse, EWMStorageType]
      - name: $expand
        in: query
        description: Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand)
        explode: false
        schema:
          type: array
          uniqueItems: true
          items:
            type: string
            enum: ['*', _Warehouse]
      responses:
        '200':
          description: Retrieved entities
          content:
            application/json:
              schema:
                title: Collection of WarehouseStorageTypeType
                type: object
                properties:
                  '@odata.count': {$ref: '#/components/schemas/count'}
                  value:
                    type: array
                    items: {$ref: '#/components/schemas/com.sap.gateway.srvd_a2x.api_warehouse_2.v0001.WarehouseStorageTypeType'}
        4XX: {$ref: '#/components/responses/error'}
  /WarehouseStorageType/{EWMWarehouse}/{EWMStorageType}:
    parameters:
    - name: EWMWarehouse
      in: path
      required: true
      description: Warehouse Number/Warehouse Complex
      schema: {type: string, maxLength: 4}
    - name: EWMStorageType
      in: path
      required: true
      description: Storage Type
      schema: {type: string, maxLength: 4}
    get:
      summary: Get entity from WarehouseStorageType by key
      tags: [Warehouse Storage Type]
      parameters:
      - name: $select
        in: query
        description: Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect)
        explode: false
        schema:
          type: array
          uniqueItems: true
          items:
            type: string
            enum: [EWMWarehouse, EWMStorageType]
      - name: $expand
        in: query
        description: Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand)
        explode: false
        schema:
          type: array
          uniqueItems: true
          items:
            type: string
            enum: ['*', _Warehouse]
      responses:
        '200':
          description: Retrieved entity
          content:
            application/json:
              schema: {$ref: '#/components/schemas/com.sap.gateway.srvd_a2x.api_warehouse_2.v0001.WarehouseStorageTypeType'}
        4XX: {$ref: '#/components/responses/error'}
  /WarehouseStorageType/{EWMWarehouse}/{EWMStorageType}/_Warehouse:
    parameters:
    - name: EWMWarehouse
      in: path
      required: true
      description: Warehouse Number/Warehouse Complex
      schema: {type: string, maxLength: 4}
    - name: EWMStorageType
      in: path
      required: true
      description: Storage Type
      schema: {type: string, maxLength: 4}
    get:
      summary: Get related _Warehouse
      tags: [Warehouse Storage Type, Warehouse]
      parameters:
      - name: $select
        in: query
        description: Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect)
        explode: false
        schema:
          type: array
          uniqueItems: true
          items:
            type: string
            enum: [EWMWarehouse]
      - name: $expand
        in: query
        description: Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand)
        explode: false
        schema:
          type: array
          uniqueItems: true
          items:
            type: string
            enum: ['*', _WarehouseStorageType]
      responses:
        '200':
          description: Retrieved entity
          content:
            application/json:
              schema: {$ref: '#/components/schemas/com.sap.gateway.srvd_a2x.api_warehouse_2.v0001.WarehouseType'}
        4XX: {$ref: '#/components/responses/error'}
  /$batch:
    post:
      summary: Send a group of requests
      description: |-
        Group multiple requests into a single request payload, see [Batch Requests](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_BatchRequests).

        *Please note that "Try it out" is not supported for this request.*
      tags: [Batch Requests]
      requestBody:
        required: true
        description: Batch request
        content:
          multipart/mixed;boundary=request-separator:
            schema: {type: string}
            example: |-
              --request-separator
              Content-Type: application/http
              Content-Transfer-Encoding: binary

              GET Warehouse HTTP/1.1
              Accept: application/json


              --request-separator--
      responses:
        '200':
          description: Batch response
          content:
            multipart/mixed:
              schema: {type: string}
              example: |-
                --response-separator
                Content-Type: application/http

                HTTP/1.1 200 OK
                Content-Type: application/json

                {...}
                --response-separator--
        4XX: {$ref: '#/components/responses/error'}
components:
  schemas:
    com.sap.gateway.srvd_a2x.api_warehouse_2.v0001.WarehouseStorageTypeType:
      type: object
      properties:
        EWMWarehouse: {type: string, maxLength: 4, title: Warehouse Number, description: Warehouse Number/Warehouse Complex}
        EWMStorageType: {type: string, maxLength: 4, title: Storage Type}
        _Warehouse: {$ref: '#/components/schemas/com.sap.gateway.srvd_a2x.api_warehouse_2.v0001.WarehouseType'}
      title: Warehouse Storage Type
    com.sap.gateway.srvd_a2x.api_warehouse_2.v0001.WarehouseStorageTypeType-create:
      type: object
      properties:
        _Warehouse: {$ref: '#/components/schemas/com.sap.gateway.srvd_a2x.api_warehouse_2.v0001.WarehouseType-create'}
      title: Warehouse Storage Type (for create)
    com.sap.gateway.srvd_a2x.api_warehouse_2.v0001.WarehouseStorageTypeType-update: {type: object, title: Warehouse Storage Type (for update)}
    com.sap.gateway.srvd_a2x.api_warehouse_2.v0001.WarehouseType:
      type: object
      properties:
        EWMWarehouse: {type: string, maxLength: 4, title: Warehouse Number, description: Warehouse Number/Warehouse Complex}
        _WarehouseStorageType:
          type: array
          items: {$ref: '#/components/schemas/com.sap.gateway.srvd_a2x.api_warehouse_2.v0001.WarehouseStorageTypeType'}
      title: Warehouse
    com.sap.gateway.srvd_a2x.api_warehouse_2.v0001.WarehouseType-create:
      type: object
      properties:
        _WarehouseStorageType:
          type: array
          items: {$ref: '#/components/schemas/com.sap.gateway.srvd_a2x.api_warehouse_2.v0001.WarehouseStorageTypeType-create'}
      title: Warehouse (for create)
    com.sap.gateway.srvd_a2x.api_warehouse_2.v0001.WarehouseType-update: {type: object, title: Warehouse (for update)}
    count:
      anyOf:
      - {type: number}
      - {type: string}
      description: The number of entities in the collection. Available when using the [$count](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptioncount) query option.
    error:
      type: object
      required: [error]
      properties:
        error:
          type: object
          required: [code, message]
          properties:
            code: {type: string}
            message: {type: string}
            target: {type: string}
            details:
              type: array
              items:
                type: object
                required: [code, message]
                properties:
                  code: {type: string}
                  message: {type: string}
                  target: {type: string}
            innererror: {type: object, description: The structure of this object is service-specific}
  parameters:
    top:
      name: $top
      in: query
      description: Show only the first n items, see [Paging - Top](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptiontop)
      schema: {type: integer, minimum: 0}
      example: 50
    skip:
      name: $skip
      in: query
      description: Skip the first n items, see [Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionskip)
      schema: {type: integer, minimum: 0}
    count:
      name: $count
      in: query
      description: Include count of items, see [Count](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptioncount)
      schema: {type: boolean}
    search:
      name: $search
      in: query
      description: Search items by search phrases, see [Searching](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionsearch)
      schema: {type: string}
  responses:
    error:
      description: Error
      content:
        application/json:
          schema: {$ref: '#/components/schemas/error'}
  securitySchemes:
    OAuth2Auth:
      type: oauth2
      flows:
        authorizationCode:
          scopes: {'OV4:API_WAREHOUSE_2': ''}
          refreshUrl: https://{host}:{port}
          authorizationUrl: https://{host}:{port}
          tokenUrl: https://{host}:{port}
    BasicAuth: {type: http, scheme: basic}
security:
- OAuth2Auth: ['OV4:API_WAREHOUSE_2']
- BasicAuth: []
